name: release-build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
      - convert-ci-cd-to-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::865423910594:role/github-actions-trust

      - name: testAws
        run: aws s3 ls s3://plutovr/plutosphere
